### ISSUE TITLE
BackHandler is breaking react-navigation default behaviour

### ISSUE THREAD

**Issue by ddedic** [jobtoday/react-native-image-viewing#19]
As stated in title, when used inside of StackNavigator and Modal is opened for the first time, react-navigation BackHandler is not working anymore.

**Comment by KangAbbad** [comment]
Same here!

**Comment by ManigandanRaamanathan** [comment]
@ddedic @KangAbbad any update on this issue? im facing same issue

**Comment by ManigandanRaamanathan** [comment]
@ddedic @KangAbbad temporarily fixed with this terniary condition in rendering the modal:-

```
                {this.state.visibleImage? <ImageView
                    images={this.state.previewImage}
                    imageIndex={0}
                    visible={this.state.visibleImage}
                    onRequestClose={() => this.setState({visibleImage: false})}
                    hideStatusBar={true}
                /> : null}
```

**Comment by bj2jung** [comment]
Same issue here

**Comment by maksimko** [comment]
@ddedic @KangAbbad @bj2jung @ManigandanRaamanathan 
Hi fellas,
do you mind to test if [this PR](https://github.com/jobtoday/react-native-image-viewing/commit/170ae9d993893113ed356dc126858b8235b577ca) fix an issue?
It's based on @ManigandanRaamanathan suggestion.
Thanks!

**Comment by Tweenkie** [comment]
Probably caused by the backHandler leak in Modal.android.tsx

**Comment by antonKalinin** [comment]
Thanks everyone and especially @maksimko for PR, should be resolved in v0.1.8

**Comment by eminsr** [comment]
> Thanks everyone and especially @maksimko for PR, should be resolved in v0.1.8

Unfortunately, it is not fixed for me. I don't think `return null` stops `useEffect` from working. I didn't try @Tweenkie 's solution but it should work ok. https://github.com/jobtoday/react-native-image-viewing/pull/29
Or you can just `return visible` like this.

```
const backHandler = BackHandler.addEventListener("hardwareBackPress", () => {
            if (typeof onRequestClose === "function") {
                onRequestClose();
            }
            return visible; //HERE
        });
```
